work on integrating new nsmenufx utility
also re-added application logo from previous ‘nsmenufx’ branch (which
has nothing to do with menus, but for some reason, it was on that
branch.

as far as the nsmenufx integration goes, it’s building ok but still
gets this error when the assembly is launched:

org.osgi.framework.BundleException: Unresolved constraint in bundle
org.daisy.pipeline.gui [116]: Unable to resolve 116.0: missing
requirement [116.0] osgi.wiring.package;
(&(osgi.wiring.package=org.daisy.pipeline.clients)(version>=2.0.0)(!(ver
sion>=3.0.0)))